### ISSUE TITLE
KeyError: 'global_step'

### ISSUE THREAD

**Issue by ymuang** [KellyYutongHe/mpgd_pytorch#2]
hello , I put the CelebA-HQ model downloaded in Pretrained LDMs to ./nonlinear/SD_style/models/ldm/celeba256/ ,then I run `python main.py -i ae -s faceid --doc celeba_hq --timesteps 50 --rho_scale 0.015 --stop 100 --batch_size 1 --eta 0.5 --ref_path ./images/294.jpg --repeat 1 --ldm_start 500 --ldm_end 300` , Then un error occurred: 
ERROR - main.py - 2024-05-26 00:34:08,478 - Traceback (most recent call last):
  File "main.py", line 181, in main
    runner.sample(args.sample_strategy)
  File "/root/autodl-tmp/mpgd/nonlinear/Face-GD/runners/diffusion.py", line 156, in sample
    self.sample_faceid(model, mode)
  File "/root/autodl-tmp/mpgd/nonlinear/Face-GD/runners/diffusion.py", line 253, in sample_faceid
    ldm_model, _ = load_model(config, ckpt, gpu, eval_mode)
  File "/root/autodl-tmp/mpgd/nonlinear/Face-GD/runners/diffusion.py", line 42, in load_model
    global_step = pl_sd["global_step"]
KeyError: 'global_step'
How to resolve it ? Is it because I placed the model in the wrong location, or is there another reason?Please,thank you

**Comment by KellyYutongHe** [comment]
Hi! I think you will have to unzip the zipped file in the corresponding folder

**Comment by ymuang** [comment]
thank you for your response!

牟洋
***@***.***

签名由 网易灵犀办公 定制


Original:
From:Kelly (Yutong) He< ***@***.***>Date:2024-05-27 17:48:58To:KellyYutongHe/mpgd_pytorch< ***@***.***>Cc:ymuang< ***@***.***>、Author< ***@***.***>Subject:Re: [KellyYutongHe/mpgd_pytorch] KeyError: 'global_step' (Issue #2)
Hi! I think you will have to unzip the zipped file in the corresponding folder
