### ISSUE TITLE
ImageNet model is not good

### ISSUE THREAD

**Issue by jinwoolim8180** [KellyYutongHe/mpgd_pytorch#3]
![image](https://github.com/user-attachments/assets/24a05117-b148-4760-b944-0a1b0c1dc248)

I tried to use the ImageNet model uploaded in your Google Drive, but it only reconstructs a noise above.
Is the uploaded model a correct model?

**Comment by KellyYutongHe** [comment]
Is this an unconditional sample from this model?

**Comment by jinwoolim8180** [comment]
No, I ran a model on this model_config:

`# Defaults for image training.

image_size: 256
num_channels: 128
num_res_blocks: 1
channel_mult: ""
learn_sigma: True
class_cond: False
use_checkpoint: False
attention_resolutions: 16
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.0
resblock_updown: True
use_fp16: False
use_new_attention_order: False

model_path: models/imagenet256.pt`

and I tried to super-resolution this image with MPGD-AE:

![image](https://github.com/user-attachments/assets/b587bb44-0aaa-4abf-8e1b-c80dd2c02ed0)

It would be nice of you if you could try this image on your model, please.

**Comment by KellyYutongHe** [comment]
The link is provided by the authors of DPS and was only intended for downloading the FFHQ model. You will have to use the model config here in order to run ImageNet: https://github.com/DPS2022/diffusion-posterior-sampling/blob/main/configs/imagenet_model_config.yaml

**Comment by jinwoolim8180** [comment]
Thank you! Thanks for quick and kind responses. It works alright!
